package service
package service

import (
	"testing"
	"time"

	"github.com/Prakash-sa/terraform-aws/app/pkg/ai"
	"github.com/Prakash-sa/terraform-aws/app/pkg/models"
	"go.uber.org/zap"
)

// MockAIClient is a mock implementation of the AI client for testing




































































































































































































































































































































































































































}	}		t.Error("ResolvedAt should be nil for open incidents")	if incident.ResolvedAt != nil {	}		t.Error("UpdatedAt timestamp is not correct")	if incident.UpdatedAt.Before(beforeCreate) || incident.UpdatedAt.After(afterCreate) {	}		t.Error("CreatedAt timestamp is not correct")	if incident.CreatedAt.Before(beforeCreate) || incident.CreatedAt.After(afterCreate) {	afterCreate := time.Now()	incident, _ := service.CreateIncident(req)	}		Description: "Test Description",		Title:       "Test Incident",	req := &models.CreateIncidentRequest{		beforeCreate := time.Now()	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestIncidentTimestamps(t *testing.T) {}	}		t.Errorf("Expected 10 incidents, got %d", len(incidents))	if len(incidents) != 10 {	incidents, _ := service.ListIncidents(nil, nil)	// Verify all were created	}		<-done	for i := 0; i < 10; i++ {	// Wait for all goroutines	}		}(i)			done <- true			service.CreateIncident(req)			}				Description: "Test Description",				Title:       "Concurrent Incident " + string(rune(index)),			req := &models.CreateIncidentRequest{		go func(index int) {	for i := 0; i < 10; i++ {	done := make(chan bool, 10)	// Test concurrent creates	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestConcurrentOperations(t *testing.T) {}	}		t.Error("Summary should not be empty")	if summary.Summary == "" {	}		t.Error("AI client SummarizeLogs method should be called")	if !mockAI.summarizeLogsCalled {	}		t.Fatalf("SummarizeLogs failed: %v", err)	if err != nil {	summary, err := service.SummarizeLogs(logs)	logs := []string{"Log 1", "Log 2", "Log 3"}	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestSummarizeLogs(t *testing.T) {}	}		t.Error("RCA root cause should not be empty")	if rca.RCADocument.RootCause == "" {	}		t.Error("AI client GenerateRCA method should be called")	if !mockAI.generateRCACalled {	}		t.Error("RCADocument should not be nil")	if rca.RCADocument == nil {	}		t.Fatalf("GenerateRCA failed: %v", err)	if err != nil {	rca, err := service.GenerateRCA(created.ID)	// Generate RCA	created, _ := service.CreateIncident(req)	}		Description: "Test Description",		Title:       "Test Incident",	req := &models.CreateIncidentRequest{	// Create an incident	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestGenerateRCA(t *testing.T) {}	}		t.Error("Analysis summary should not be empty")	if analyzed.AIAnalysis.Summary == "" {	}		t.Error("AI client analyze method should be called")	if !mockAI.analyzeCalled {	}		t.Error("AIAnalysis should not be nil")	if analyzed.AIAnalysis == nil {	}		t.Fatalf("AnalyzeIncident failed: %v", err)	if err != nil {	analyzed, err := service.AnalyzeIncident(created.ID)	// Analyze it	created, _ := service.CreateIncident(req)	}		Logs:        []string{"Log 1", "Log 2"},		Description: "Test Description",		Title:       "Test Incident",	req := &models.CreateIncidentRequest{	// Create an incident	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestAnalyzeIncident(t *testing.T) {}	}		t.Error("Expected error when retrieving deleted incident")	if err == nil {	_, err = service.GetIncident(created.ID)	// Verify it's gone	}		t.Fatalf("DeleteIncident failed: %v", err)	if err != nil {	err := service.DeleteIncident(created.ID)	// Delete it	created, _ := service.CreateIncident(req)	}		Description: "Test Description",		Title:       "Test Incident",	req := &models.CreateIncidentRequest{	// Create an incident	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestDeleteIncident(t *testing.T) {}	}		t.Error("ResolvedAt should be after UpdatedAt")	if updated.ResolvedAt.Before(created.UpdatedAt) {	}		t.Error("ResolvedAt should be set when status changes to resolved")	if updated.ResolvedAt == nil {	updated, _ := service.UpdateIncident(created.ID, updateReq)	}		Status: &status,	updateReq := &models.UpdateIncidentRequest{	status := models.StatusResolved	created, _ := service.CreateIncident(req)	}		Description: "Test Description",		Title:       "Test Incident",	req := &models.CreateIncidentRequest{	// Create and resolve an incident	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestUpdateIncidentResolved(t *testing.T) {}	}		t.Errorf("Expected status %s, got %s", newStatus, updated.Status)	if updated.Status != newStatus {	}		t.Errorf("Expected title %s, got %s", newTitle, updated.Title)	if updated.Title != newTitle {	}		t.Fatalf("UpdateIncident failed: %v", err)	if err != nil {	updated, err := service.UpdateIncident(created.ID, updateReq)	}		Status: &newStatus,		Title:  &newTitle,	updateReq := &models.UpdateIncidentRequest{	newStatus := models.StatusInProgress	newTitle := "Updated Title"	// Update it	created, _ := service.CreateIncident(req)	}		Description: "Original Description",		Title:       "Original Title",	req := &models.CreateIncidentRequest{	// Create an incident	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestUpdateIncident(t *testing.T) {}	}		t.Error("Expected to find at least 1 high severity incident")	if len(incidents) < 1 {	}		t.Fatalf("ListIncidents failed: %v", err)	if err != nil {	incidents, err := service.ListIncidents(nil, &severity)	// Filter by severity	service.CreateIncident(req)	}		Severity:    &severity,		Description: "Critical error in production",		Title:       "High Severity Incident",	req := &models.CreateIncidentRequest{	severity := models.SeverityHigh	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestListIncidentsWithFilter(t *testing.T) {}	}		t.Errorf("Expected 3 incidents, got %d", len(incidents))	if len(incidents) != 3 {	}		t.Fatalf("ListIncidents failed: %v", err)	if err != nil {	incidents, err := service.ListIncidents(nil, nil)	}		service.CreateIncident(req)		}			Description: "Test Description",			Title:       "Test Incident " + string(rune(i)),		req := &models.CreateIncidentRequest{	for i := 0; i < 3; i++ {	// Create multiple incidents	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestListIncidents(t *testing.T) {}	}		t.Error("Expected error for nonexistent incident")	if err == nil {	_, err := service.GetIncident("nonexistent")	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestGetIncidentNotFound(t *testing.T) {}	}		t.Errorf("Expected ID %s, got %s", created.ID, retrieved.ID)	if retrieved.ID != created.ID {	}		t.Fatalf("GetIncident failed: %v", err)	if err != nil {	retrieved, err := service.GetIncident(created.ID)	// Retrieve it	created, _ := service.CreateIncident(req)	}		Description: "Test Description",		Title:       "Test Incident",	req := &models.CreateIncidentRequest{	// Create an incident	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestGetIncident(t *testing.T) {}	}		t.Error("Severity should be classified")	if incident.Severity == "" {	}		t.Errorf("Expected status %s, got %s", models.StatusOpen, incident.Status)	if incident.Status != models.StatusOpen {	}		t.Errorf("Expected title %s, got %s", req.Title, incident.Title)	if incident.Title != req.Title {	}		t.Error("Incident ID should not be empty")	if incident.ID == "" {	}		t.Fatalf("CreateIncident failed: %v", err)	if err != nil {	incident, err := service.CreateIncident(req)	}		Tags:        []string{"test"},		Logs:        []string{"Log 1", "Log 2"},		Source:      "test",		Description: "Test Description",		Title:       "Test Incident",	req := &models.CreateIncidentRequest{	service := NewIncidentService(store, mockAI, logger)	mockAI := &MockAIClient{}	store := NewIncidentStore()	logger, _ := zap.NewDevelopment()func TestCreateIncident(t *testing.T) {// Tests}	return "gpt-4"func (m *MockAIClient) Model() string {}	return ai.ProviderOpenAIfunc (m *MockAIClient) Provider() ai.Provider {}	return nilfunc (m *MockAIClient) Health(ctx interface{}) error {}	}, nil		Alerts:      []string{"Alert 1"},		KeyInsights: []string{"Insight 1", "Insight 2"},		Summary:     "Log analysis summary",	return &ai.SummarizeResponse{	}		return nil, ai.ErrInvalidResponse	if m.shouldError {	m.summarizeLogsCalled = truefunc (m *MockAIClient) SummarizeLogs(ctx interface{}, req ai.SummarizeRequest) (*ai.SummarizeResponse, error) {}	}, nil		LessonsLearned:     []string{"Lesson 1", "Lesson 2"},		PreventiveMeasures: []string{"Increase pool size", "Add monitoring"},		ImmediateResolution: "Restarted database service",		Impact:             "Service unavailable for 15 minutes",		RootCause:          "Database connection pool exhaustion",		Timeline:           "Timeline: incident started at T0",	return &ai.RCAResponse{	}		return nil, ai.ErrInvalidResponse	if m.shouldError {	m.generateRCACalled = truefunc (m *MockAIClient) GenerateRCA(ctx interface{}, req ai.RCARequest) (*ai.RCAResponse, error) {}	}, nil		SuggestedSeverity:  "high",		RecommendedActions: []string{"Action 1", "Action 2"},		RootCauses:         []string{"Root cause 1"},		Findings:           []string{"Finding 1", "Finding 2"},		Summary:            "Test incident analysis",	return &ai.AnalysisResponse{	}		return nil, ai.ErrInvalidResponse	if m.shouldError {	m.analyzeCalled = truefunc (m *MockAIClient) AnalyzeIncident(ctx interface{}, req ai.AnalysisRequest) (*ai.AnalysisResponse, error) {}	shouldError        bool	summarizeLogsCalled bool	generateRCACalled  bool	analyzeCalled      booltype MockAIClient struct {