package handlers
package handlers

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gorilla/mux"
	"github.com/Prakash-sa/terraform-aws/app/pkg/models"
	"github.com/Prakash-sa/terraform-aws/app/pkg/service"

















































































































































































































































































}	}		t.Errorf("Expected status 400, got %d", w.Code)	if w.Code != http.StatusBadRequest {	handler.SummarizeLogs(w, req)	w := httptest.NewRecorder()	req := httptest.NewRequest("POST", "/api/v1/logs/summarize", bytes.NewBuffer(body))	body, _ := json.Marshal(reqBody)	}		Logs: []string{},	reqBody := models.LogSummarizeRequest{	handler, _ := setupTestHandler(t)func TestSummarizeLogsEmptyLogs(t *testing.T) {}	}		t.Error("Summary should not be empty")	if response.Summary == "" {	json.NewDecoder(w.Body).Decode(&response)	var response models.LogSummarizeResponse	}		t.Errorf("Expected status 200, got %d", w.Code)	if w.Code != http.StatusOK {	handler.SummarizeLogs(w, req)	w := httptest.NewRecorder()	req := httptest.NewRequest("POST", "/api/v1/logs/summarize", bytes.NewBuffer(body))	body, _ := json.Marshal(reqBody)	}		Logs: []string{"Log 1", "Log 2", "Log 3"},	reqBody := models.LogSummarizeRequest{	handler, _ := setupTestHandler(t)func TestSummarizeLogsHandler(t *testing.T) {}	}		t.Error("Expected error when retrieving deleted incident")	if err == nil {	_, err := service.GetIncident(incident.ID)	// Verify it's gone	}		t.Errorf("Expected status 204, got %d", w.Code)	if w.Code != http.StatusNoContent {	handler.DeleteIncident(w, req)	w := httptest.NewRecorder()	req = mux.SetURLVars(req, map[string]string{"id": incident.ID})	req := httptest.NewRequest("DELETE", "/api/v1/incidents/"+incident.ID, nil)	// Delete it	incident, _ := service.CreateIncident(createReq)	}		Description: "Test Description",		Title:       "Test Incident",	createReq := &models.CreateIncidentRequest{	// Create an incident	handler, service := setupTestHandler(t)func TestDeleteIncidentHandler(t *testing.T) {}	}		t.Errorf("Expected title %s, got %s", newTitle, updated.Title)	if updated.Title != newTitle {	json.NewDecoder(w.Body).Decode(&updated)	var updated models.Incident	}		t.Errorf("Expected status 200, got %d", w.Code)	if w.Code != http.StatusOK {	handler.UpdateIncident(w, req)	w := httptest.NewRecorder()	req = mux.SetURLVars(req, map[string]string{"id": incident.ID})	req := httptest.NewRequest("PUT", "/api/v1/incidents/"+incident.ID, bytes.NewBuffer(body))	body, _ := json.Marshal(updateReq)	}		Status: &newStatus,		Title:  &newTitle,	updateReq := models.UpdateIncidentRequest{	newStatus := models.StatusInProgress	newTitle := "Updated Title"	// Update it	incident, _ := service.CreateIncident(createReq)	}		Description: "Test Description",		Title:       "Original Title",	createReq := &models.CreateIncidentRequest{	// Create an incident	handler, service := setupTestHandler(t)func TestUpdateIncidentHandler(t *testing.T) {}	}		t.Errorf("Expected 3 incidents, got %d", len(incidents))	if len(incidents) != 3 {	json.NewDecoder(w.Body).Decode(&incidents)	var incidents []*models.Incident	}		t.Errorf("Expected status 200, got %d", w.Code)	if w.Code != http.StatusOK {	handler.ListIncidents(w, req)	w := httptest.NewRecorder()	req := httptest.NewRequest("GET", "/api/v1/incidents", nil)	}		service.CreateIncident(req)		}			Description: "Test Description",			Title:       "Test Incident",		req := &models.CreateIncidentRequest{	for i := 0; i < 3; i++ {	// Create multiple incidents	handler, service := setupTestHandler(t)func TestListIncidentsHandler(t *testing.T) {}	}		t.Errorf("Expected status 404, got %d", w.Code)	if w.Code != http.StatusNotFound {	handler.GetIncident(w, req)	w := httptest.NewRecorder()	req = mux.SetURLVars(req, map[string]string{"id": "nonexistent"})	req := httptest.NewRequest("GET", "/api/v1/incidents/nonexistent", nil)	handler, _ := setupTestHandler(t)func TestGetIncidentNotFound(t *testing.T) {}	}		t.Errorf("Expected ID %s, got %s", incident.ID, retrieved.ID)	if retrieved.ID != incident.ID {	json.NewDecoder(w.Body).Decode(&retrieved)	var retrieved models.Incident	}		t.Errorf("Expected status 200, got %d", w.Code)	if w.Code != http.StatusOK {	handler.GetIncident(w, req)	w := httptest.NewRecorder()	req = mux.SetURLVars(req, map[string]string{"id": incident.ID})	req := httptest.NewRequest("GET", "/api/v1/incidents/"+incident.ID, nil)	// Get it via handler	incident, _ := service.CreateIncident(createReq)	}		Description: "Test Description",		Title:       "Test Incident",	createReq := &models.CreateIncidentRequest{	// Create an incident first	handler, service := setupTestHandler(t)func TestGetIncidentHandler(t *testing.T) {}	}		t.Errorf("Expected status 400, got %d", w.Code)	if w.Code != http.StatusBadRequest {	handler.CreateIncident(w, req)	w := httptest.NewRecorder()	req := httptest.NewRequest("POST", "/api/v1/incidents", bytes.NewBuffer(body))	body, _ := json.Marshal(reqBody)	}		// Missing Description		Title: "Test Incident",	reqBody := models.CreateIncidentRequest{	handler, _ := setupTestHandler(t)func TestCreateIncidentMissingFields(t *testing.T) {}	}		t.Error("Incident ID should not be empty")	if incident.ID == "" {	}		t.Errorf("Expected title %s, got %s", reqBody.Title, incident.Title)	if incident.Title != reqBody.Title {	json.NewDecoder(w.Body).Decode(&incident)	var incident models.Incident	}		t.Errorf("Expected status 201, got %d", w.Code)	if w.Code != http.StatusCreated {	handler.CreateIncident(w, req)	w := httptest.NewRecorder()	req := httptest.NewRequest("POST", "/api/v1/incidents", bytes.NewBuffer(body))	body, _ := json.Marshal(reqBody)	}		Source:      "test",		Description: "Test Description",		Title:       "Test Incident",	reqBody := models.CreateIncidentRequest{	handler, _ := setupTestHandler(t)func TestCreateIncidentHandler(t *testing.T) {}	return handler, service		handler := NewIncidentHandler(service, logger)	service := service.NewIncidentService(store, nil, logger)	// Type assertion for the real AI client interface		mockAI := &MockAIClientForHandlers{}	// Create a mock AI client		store := service.NewIncidentStore()	logger, _ := zap.NewDevelopment()func setupTestHandler(t *testing.T) (*IncidentHandler, *service.IncidentService) {}	return "gpt-4"func (m *MockAIClientForHandlers) Model() string {}	return "openai"func (m *MockAIClientForHandlers) Provider() interface{} {}	return nilfunc (m *MockAIClientForHandlers) Health(ctx interface{}) error {}	return nil, nilfunc (m *MockAIClientForHandlers) SummarizeLogs(ctx interface{}, req interface{}) (*interface{}, error) {}	return nil, nilfunc (m *MockAIClientForHandlers) GenerateRCA(ctx interface{}, req interface{}) (*interface{}, error) {}	return nil, nilfunc (m *MockAIClientForHandlers) AnalyzeIncident(ctx interface{}, req interface{}) (*interface{}, error) {type MockAIClientForHandlers struct{}// MockAIClientForHandlers is a mock AI client for handler tests)	"go.uber.org/zap"